Hostboot FW SubSystem Version Support
open-power/op-build pull request #4539
Opened 2022-02-11 17:04 UTC by debmc

Provide the ability to seed the Hostboot images with the OP Build long and short
version of the FW Images which are included in the Hostboot binaries to correctly
identify the image being used (even post Concurrent Update at Hostboot Runtime).

2022-02-11 19:29 UTC, dcrowell77 commented on openpower/package/pkg-versions.mk
> +if [ "HOSTBOOT_P10" == "$(2)" ]; then \
For future-proofing it would be better if this excluded the P8/P9 paths rather than forcing us to change this again in P11, etc.

2022-02-11 19:30 UTC, dcrowell77 requested changes
future proof it

2022-02-21 20:09 UTC, velozr commented
Looks good to me

2022-02-21 21:08 UTC, velozr approved these changes
Looks good

2022-02-21 21:08 UTC, velozr commented on openpower/package/hostboot-p10/hostboot-p10.mk
> +    HOSTBOOT_VERSION=`cat $(HOSTBOOT_P10_VERSION_FILE)` \
Looks good

2022-03-03 17:27 UTC, dcrowell77 approved these changes

2022-03-04 14:40 UTC, merged